"""added user_type field to denote mentor/mentee

Revision ID: b108e9c71a92
Revises: 
Create Date: 2019-11-29 19:30:59.011950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b108e9c71a92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('user_type', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'user_type')
    # ### end Alembic commands ###
